### ISSUE TITLE
如何得到value的值？

### ISSUE THREAD

**Issue by luckypoem** [dns-sb/DoT#2]
hi

我看了https://github.com/dns-sb/DoT/blob/master/example/stubby.yml ，但是如何得到value的值？
upstream_recursive_servers:
  - address_data: 185.222.222.222
    tls_auth_name: "dns.sb"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: /qCm+kZoAyouNBtgd1MPMS/cwpN4KLr60bAtajPLt0k=

我在自己的vps上搭建了dot server

**Comment by Showfom** [comment]
HTTP Public Key Pinning (HPKP)

https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning

**Comment by luckypoem** [comment]
我用你的stubby.yml文件：https://github.com/dns-sb/DoT/raw/master/example/stubby.yml ，下载到
/usr/local/etc/stubby/里面，替换了原有的stubby.yml ，
运行：sudo stubby -C /usr/local/etc/stubby/stubby.yml可以解决dns污染问题。
但是在我替换：
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list: 
  - GETDNS_TRANSPORT_TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 256
edns_client_subnet_private : 1
idle_timeout: 10000
listen_addresses:
  - 127.0.0.1
  -  0::1
round_robin_upstreams: 1
upstream_recursive_servers:
  - address_data: 185.222.222.222
    tls_auth_name: "dns.sb"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: /qCm+kZoAyouNBtgd1MPMS/cwpN4KLr60bAtajPLt0k=

为：
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list: 
  - GETDNS_TRANSPORT_TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 256
edns_client_subnet_private : 1
idle_timeout: 10000
listen_addresses:
  - 127.0.0.1
  -  0::1
round_robin_upstreams: 1
upstream_recursive_servers:
  - address_data: my-vps-ip
    tls_auth_name: "mydomain.com"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: 我的value的值

然后，运行：sudo stubby -C /usr/local/etc/stubby/stubby.yml ，遇错：
Could not configure context with config dict: The library did not have the requested API feature implemented.
Could not parse config file "/usr/local/etc/stubby/stubby.yml": The library did not have the requested API feature implemented.

怎么回事？怎么解决问题？

**Comment by Showfom** [comment]
你发错地方了吧，你这个问题得去 https://github.com/getdnsapi/stubby 发求助

**Comment by luckypoem** [comment]
可能是我的dot server并没有真正搭建成功导致的错误。你的dot server是用什么程序搭建的？可写篇详细的wiki文章放在你这个项目的wiki里吗？

**Comment by Showfom** [comment]
unbound 搭建的，暂时没有时间写教程

**Comment by luckypoem** [comment]
此命令：echo | openssl s_client -connect 'mydomain.com:853' 2> /dev/null | openssl x509 -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64
里面的pubkey和pkey需要分别替换为从服务器上下载的证书文件和私匙文件吗

**Comment by Showfom** [comment]
年代久远。。。已经忘记 下次重新续费证书的时候再研究，你先自己研究吧

**Comment by Showfom** [comment]
```
echo | openssl s_client -connect 192.168.100.53:853 2>/dev/null | openssl x509 -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64
```

Ref https://blog.apnic.net/2020/02/28/how-to-deploy-dot-and-doh-with-dnsdist/
