### ISSUE TITLE
DoT is blocked in China Mainland

### ISSUE THREAD

**Issue by fxzxmicah** [dns-sb/DoT#3]
![image](https://user-images.githubusercontent.com/48860358/126037388-5b6f9d72-e430-4864-85df-d69e1726034d.png)

**Comment by Showfom** [comment]
Our DoT servers are working fine, seems you are from China, the standard DoT port 853 has been blocked by GFW.

There's no way to solve this problem, we suggest do not use DoT in China.

**Comment by fxzxmicah** [comment]
OK, fine.
