### ISSUE TITLE
about #index part of unbound.conf

### ISSUE THREAD

**Issue by youxiaojie** [dns-sb/DoT#4]
dear sir,
 I noticed the official man page introduce # part to show domain name
`each server you will need to specify that the connection port using @, and you will also need to indicate which is its domain name with #. Even though it looks like an comment the hashtag name allows for the TLS authentication name to be set for stub-zones and with unbound-control forward control command. There should not be any spaces between the @ and # markups. `
from wiki of archliux.
however your unbound.conf omit #part, is it an error?
thanks!

**Comment by Showfom** [comment]
Only IPv6 address needs domain, I have added it.
