### ISSUE TITLE
Weird failure on Android 11 via DTAG.

### ISSUE THREAD

**Issue by kRush-** [dns-sb/DoT#5]
Saturday afternoon I noticed my phone would start complaining about `Private DNS Server cannot be accessed` over my home WiFi (which is a Telekom DSL+LTE Hybrid connection), if it is set to dot.sb.
It is currently working over mobile connection (which is T-Mobile), although that intermittently failed on Sunday, too.
Since my brother's Android 12 phone and my Linux laptop is having no such issues, I suspect some certificate shenanigans with a subset of your resolvers?

![logcat](https://user-images.githubusercontent.com/5452485/178426193-9bee6e68-b527-40cc-8651-7152c2eb7575.png)

That SSL_connect error does not occur when using dns.quad9.net and I can resolve $random-dnsotls-ds.metric.gstatic.com via my router's DNS.
Let me know if I should provide more detailed info.

**Comment by Showfom** [comment]
```
# kdig example.com +tls @185.222.222.222
;; TLS session (TLS1.3)-(ECDHE-SECP256R1)-(ECDSA-SECP256R1-SHA256)-(AES-256-GCM)
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 39066
;; Flags: qr rd ra; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 1

;; EDNS PSEUDOSECTION:
;; Version: 0; flags: ; UDP size: 512 B; ext-rcode: NOERROR

;; QUESTION SECTION:
;; example.com.        		IN	A

;; ANSWER SECTION:
example.com.        	45281	IN	A	93.184.216.34

;; Received 56 B
;; Time 2022-07-12 10:57:13 UTC
;; From 185.222.222.222@853(TCP) in 2.5 ms
```

also for the `gstatic.com` domain queries

```
# kdig 900912f0-dnsotls-ds.metric.gstatic.com +tls @185.222.222.222
;; TLS session (TLS1.3)-(ECDHE-SECP256R1)-(ECDSA-SECP256R1-SHA256)-(AES-256-GCM)
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 45428
;; Flags: qr rd ra; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 1

;; EDNS PSEUDOSECTION:
;; Version: 0; flags: ; UDP size: 512 B; ext-rcode: NOERROR

;; QUESTION SECTION:
;; 900912f0-dnsotls-ds.metric.gstatic.com. 	IN	A

;; ANSWER SECTION:
900912f0-dnsotls-ds.metric.gstatic.com. 300	IN	A	172.217.164.3

;; Received 83 B
;; Time 2022-07-12 10:58:30 UTC
;; From 185.222.222.222@853(TCP) in 19.9 ms
```

I didn't see problem with our DoT servers in Frankfurt, can you try it on your PC?

But yes, we updated our SSL certificates recently.

**Comment by kRush-** [comment]
> can you try it on your PC?

My PC was never affected, so output is the same.

Oddly enough, my phone also went back from permanent failure to working (almost) all of the time on it's own. If you changed something on your end it seems to have fixed it. If not, I'm completely clueless as to what was wrong in the first place / don't need to / can't debug any further, so I'll close this and come back if the problem reappears.
Thanks for running the service.

**Comment by Showfom** [comment]
@kRush- Because we enabled TLS 1.2 again, seems your phone is not working with TLS 1.3.
