### ISSUE TITLE
Do we need yogaDNS if configured DoT dns on router?

### ISSUE THREAD

**Issue by masterofobzene** [dns-sb/DoT#7]
I have set up DoT dns servers as my dns default servers in the router.
My router doesn't have DoT special settings, so I've set them as "normal dns" (ip addresses only).

going to Dot.sb page says that my requests are being encrypted. 
I'm worried that the webpage reads the dns server's ip and tells me that everything is fine but the requests are not being sent in the correct port therefore not really encrypted... 

My router is a TP-Link Archer vr400

Do you think this works as intended?

**Comment by Showfom** [comment]
Regular DNS is not encrypted, your ISP can still read your DNS requests, so it's better to use 3rd client in your PC for DNS requests encryption.

**Comment by masterofobzene** [comment]
Just to be clear, I 've set up the DoT dns's from dot.sb where the "normal" dns would go, without specifying ports or anything. 
Sorry if I'm repeating myself but just want to make sure we are talking the same, before installing yogadns again.

![imagen](https://user-images.githubusercontent.com/94469116/189573465-3cb7708c-5293-4adf-a3f3-4d673688b795.png)

![imagen](https://user-images.githubusercontent.com/94469116/189573529-c1cd0168-9ba6-428c-83ed-513294ab0963.png)

Do I install it again? (yogaDNS)
